version: '3.9'
services:
  rwtserver:
    image: cirune/rwtserver
    container_name: rimworld-server
    ports:
      - "25555:25555"
    volumes:
      - ./data:/RWTServer
    restart: always
    networks:
      rimworld_frontend:
networks:
  rimworld_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
