version: '3.9'
################################ Services
services:
  rwtserver:
    #image: cirune/rwtserver:0.1
    build: .
    container_name: rimworld-server
    ports:
      - "25555:25555"
    volumes:
      - ./data:/RWTServer
    restart: always
    stdin_open: true
    tty: true
    networks:
      rimworld_frontend:
    labels:
# Treafik Labels
      - traefik.enable=true
      - traefik.tcp.routers.rwtserver.entrypoints=rwtserver
      - traefik.tcp.routers.rwtserver.rule=HostSNI(`*`)
      - traefik.tcp.routers.rwtserver.tls=false
      - traefik.tcp.routers.rwtserver.tls.passthrough=true
      - traefik.tcp.services.rwtserver.loadbalancer.server.port=25555
      - traefik.docker.network=public
networks:
  rimworld_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
