version: '3.9'
################################ Services
services:
  rwtserver:
    #image: cirune/rwtserver:0.1
    build: ./
    container_name: rimworld-server
    ports:
      - "25555:25555"
    volumes:
      - ./data:/RWTServer
    restart: always
    networks:
      rimworld_frontend:
    labels:
networks:
  rimworld_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
